library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
library(skimr)
library(janitor)
library(corrplot)
library(recipes)

install.packages("tidyverse")
install.packages("readn")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("skimr")
install.packages("janitor")
install.packages("corrplot")
install.packages("recipes")